// VERSION.H

/* Defines used for different versions */

//#define SPEAR
//#define UPLOAD
//#define JAPAN
//#define JAPDEMO
//#define SPANISH
#define GOODTIMES

/*
        Wolf3d Full v1.4 GT/ID/Activision         - define GOODTIMES
        Wolf3d Shareware v1.4                     - define UPLOAD
        Wolf3d Full v1.4 Apogee (with ReadThis)   - define none
        Spear of Destiny Full                     - define SPEAR (and GOODTIMES for no FormGen quiz)
       
        Spear Demo, Wolf3d Full v1.1 and Shareware v1.0-1.1    - can be added by the user
*/

#define DEBUGKEYS       // Comment this out to compile without the Tab debug keys
#define ARTSEXTERN
#define DEMOSEXTERN
//#define MYPROFILE
//#define DEBCHECK
#define CARMACIZED
